### ISSUE TITLE
Updater security

### ISSUE THREAD

**Issue by zokradonh** [Black-Dragon131/AmongUsModManager#2]
First, thanks for this tool!

But, I have a bad feeling about the following attack vector:
As soon as someone hacked your web server he is also able to take control of all the PCs of your users.

Some asymmetric sign of the uploaded executables would be nice. You could add the cryptographic signature in the JSON and verify it. (Additionally to the sha256 corruption check)

Are you familiar with the asymmetric signature principals?

In this context: Why do we need administrative privileges at all?

**Comment by Black-Dragon131** [comment]
Hello zokradonh,

thanks for your feedback. You are right with this problem and I also thought about this problem, but wasn' t sure how to adress it right. Do you have any example code how to do what you described?
As I' m not a crypto expert, I would sign the exe after build and check if the certificate matches the one it should be signed with. But as a code signing cert is really expensive I could only do it with a self signed one. But are they unique and not reproducible?
Putting a signature in the json wouldn' t make it more secure as the json could be manipulated also or am I wrong?

The administrative privileges is needed if you installed it to program files, because the user doesn' t have write permission there.

**Comment by zokradonh** [comment]
The asymmetric signature principal allows you to create two keys. One that you have only on your machine(private key) and one that you distribute with your application(public key).
The public key can verify if a signature was signed by the private key. But is not able to create a signature. (The reason for that is Math, don't ask me for details - on RSA it has something to do with prime numbers - in ECDSA something with two points on an elliptic curve)
That is the reason why it is called asymmetric. Two keys with different purpose.

So you can create a signature for your executable and put it in the JSON. No one is able to create/fake a signature that verifies against the public key, because no one knows the private key, to create such signatures. Of course your application needs to verify the signature after downloading and before execution. But you ship the public key with the application, so that is not a problem.

I have implemented something similar here:
https://github.com/zokradonh/kangarup/blob/master/kangarup/Updater.cs

In this case I created a signature(update.sig) for the JSON itself which contains a hash of the file(that hash you already implemented). This ensures that the JSON cannot be manipulated without knowledge of the private key on your computer without being detected.

Another option would be to use [JWT](https://jwt.io/) to fully sign your json. Although not exactly the use case we have here, but maybe more simple to implement.

All of this has nothing to do with those paid code signing certificates. (Although they use the same cryptos)

**Comment by Black-Dragon131** [comment]
Thanks for your explanation. I will try and see if I can implement that.

**Comment by Black-Dragon131** [comment]
Fixed in newest version of AUMM and updater.
